//! Renders root repository instruction files from a base document and Skill usage rules.
//!
//! This module is pure composition: it decodes and normalizes the base document and projects `SkillUsage` declarations into fixed sentence forms. It does not resolve sources, inspect the manifest, or touch the filesystem; those belong to the resolution and materialization layers.
//! The composition rules are fixed by issue #38 and the root repository instructions ADR (docs/design/adr/20260803T172859Z_generate-root-repository-instructions-from-manifest.md): no template syntax, no evaluation of `when` values, verbatim insertion only.

use crate::manifest::SkillUsage;

/// The marker heading every generated root instruction file starts with.
///
/// The marker is the machine-readable claim that the file is Enozunu-owned and replaced whole on summon; edits after it are lost by design.
pub const GENERATED_MARKER: &str = "<!-- Generated by enozunu. Do not edit directly. -->";

/// Why a base document cannot be rendered.
///
/// A typed error rather than a `Diagnostic`, so the pipeline layer decides the diagnostic code and names the failing source; this module does not know which target or source failed.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RenderError {
    /// The base document bytes are not valid UTF-8. The offset is where decoding failed, so the report can point into the source file.
    InvalidUtf8 { valid_up_to: usize },
}

/// Composes the generated root instruction file from the base document bytes and the target's Skill selections.
///
/// The output is deterministic and fully normalized:
///
/// 1. the fixed generated marker;
/// 2. the base document, when non-empty, with line endings normalized to LF and trailing line terminators dropped;
/// 3. the fixed Skill usage section, when at least one Skill is selected.
///
/// Sections are separated by exactly one blank line and the output ends with exactly one LF.
/// An empty base document and an empty selection are both valid; the corresponding section is omitted rather than rendered empty.
pub fn render(base_document: &[u8], usages: &[SkillUsage]) -> Result<String, RenderError> {
    let base = std::str::from_utf8(base_document).map_err(|e| RenderError::InvalidUtf8 {
        valid_up_to: e.valid_up_to(),
    })?;

    // CRLF first so its LF is not doubled, then lone CR; the base document's inner content is otherwise preserved verbatim.
    let base = base.replace("\r\n", "\n").replace('\r', "\n");
    let base = base.trim_end_matches('\n');

    let mut sections: Vec<String> = vec![GENERATED_MARKER.to_owned()];
    if !base.is_empty() {
        sections.push(base.to_owned());
    }
    if !usages.is_empty() {
        sections.push(skill_usage_section(usages));
    }

    Ok(format!("{}\n", sections.join("\n\n")))
}

/// The fixed `## Skill usage` section: one rule per selection, or one rule per `when` of a selection.
///
/// Rule order preserves the manifest: selections in declaration order, and each selection's `when` values in declaration order.
/// A `when` value is inserted verbatim between the fixed `When ` and `, always use ...` fragments; Enozunu never evaluates or rewrites it.
fn skill_usage_section(usages: &[SkillUsage]) -> String {
    let mut lines = vec!["## Skill usage".to_owned(), String::new()];
    for usage in usages {
        if usage.whens.is_empty() {
            lines.push(format!("- Always use the `{}` skill.", usage.name));
        } else {
            for when in &usage.whens {
                lines.push(format!(
                    "- When {when}, always use the `{}` skill.",
                    usage.name
                ));
            }
        }
    }
    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn usage(name: &str, whens: &[&str]) -> SkillUsage {
        SkillUsage {
            name: name.to_owned(),
            whens: whens.iter().map(|w| (*w).to_owned()).collect(),
        }
    }

    #[test]
    fn renders_marker_base_and_skill_usage_in_fixed_order() {
        let out = render(
            b"# Project\n\nBase rules.\n",
            &[
                usage("documentation-writing", &["updating documentation"]),
                usage("code-comment", &[]),
            ],
        )
        .unwrap();
        assert_eq!(
            out,
            "<!-- Generated by enozunu. Do not edit directly. -->\n\
             \n\
             # Project\n\
             \n\
             Base rules.\n\
             \n\
             ## Skill usage\n\
             \n\
             - When updating documentation, always use the `documentation-writing` skill.\n\
             - Always use the `code-comment` skill.\n"
        );
    }

    #[test]
    fn renders_each_when_as_an_independent_rule_in_declaration_order() {
        let out = render(
            b"base",
            &[usage(
                "documentation-writing",
                &[
                    "updating documentation",
                    "writing or modifying code comments",
                ],
            )],
        )
        .unwrap();
        assert!(out.contains(
            "- When updating documentation, always use the `documentation-writing` skill.\n\
             - When writing or modifying code comments, always use the `documentation-writing` skill.\n"
        ));
    }

    #[test]
    fn omits_the_skill_usage_section_when_no_skill_is_selected() {
        let out = render(b"base only\n", &[]).unwrap();
        assert_eq!(
            out,
            "<!-- Generated by enozunu. Do not edit directly. -->\n\nbase only\n"
        );
        assert!(!out.contains("## Skill usage"));
    }

    #[test]
    fn accepts_an_empty_base_document() {
        let out = render(b"", &[usage("a", &[])]).unwrap();
        assert_eq!(
            out,
            "<!-- Generated by enozunu. Do not edit directly. -->\n\
             \n\
             ## Skill usage\n\
             \n\
             - Always use the `a` skill.\n"
        );
    }

    #[test]
    fn renders_only_the_marker_for_an_empty_base_and_no_selection() {
        let out = render(b"", &[]).unwrap();
        assert_eq!(
            out,
            "<!-- Generated by enozunu. Do not edit directly. -->\n"
        );
    }

    #[test]
    fn normalizes_crlf_and_lone_cr_to_lf() {
        let out = render(b"line1\r\nline2\rline3\n", &[]).unwrap();
        assert!(out.contains("line1\nline2\nline3\n"));
        assert!(!out.contains('\r'));
    }

    #[test]
    fn drops_only_trailing_line_terminators_from_the_base_document() {
        // Inner blank lines are content and survive; only the trailing run of line terminators is dropped before section joining, so the section separator stays exactly one blank line.
        let out = render(b"a\n\nb\r\n\r\n", &[usage("s", &[])]).unwrap();
        assert!(out.contains("a\n\nb\n\n## Skill usage"));
    }

    #[test]
    fn ends_with_exactly_one_lf() {
        for (base, usages) in [
            (&b"base\n\n\n"[..], vec![]),
            (&b""[..], vec![usage("a", &[])]),
            (&b"base"[..], vec![usage("a", &["x"])]),
        ] {
            let out = render(base, &usages).unwrap();
            assert!(out.ends_with('\n'));
            assert!(!out.ends_with("\n\n"));
        }
    }

    #[test]
    fn rejects_a_base_document_that_is_not_utf8() {
        let err = render(b"ok\xff\xfe", &[]).unwrap_err();
        assert_eq!(err, RenderError::InvalidUtf8 { valid_up_to: 2 });
    }

    #[test]
    fn inserts_when_values_verbatim() {
        // `when` is free text, never evaluated: markup-ish or sentence-like values pass through untouched.
        let out = render(
            b"",
            &[usage("s", &["the `docs/` tree changes, or a PR is opened"])],
        )
        .unwrap();
        assert!(out.contains(
            "- When the `docs/` tree changes, or a PR is opened, always use the `s` skill.\n"
        ));
    }

    #[test]
    fn renders_grouped_and_split_selections_byte_for_byte_identically() {
        // The acceptance test from issue #38: the two surface forms normalize to the same `SkillUsage` list, so the rendered section must be byte-for-byte equal.
        use crate::manifest;
        let manifest_with = |selection: &str| {
            format!(
                r#"
enozunu config-version=1 {{
  provider {{
    skills {{
      skill "a" {{ git {{ url "https://example.com/r"; branch "main"; path "s/a" }} }}
      skill "b" {{ git {{ url "https://example.com/r"; branch "main"; path "s/b" }} }}
    }}
  }}
  consumer {{
    claude {{
{selection}
    }}
  }}
}}
"#
            )
        };
        let render_of = |selection: &str| {
            let manifest = manifest::parse(&manifest_with(selection)).unwrap();
            render(
                b"base",
                &manifest.consumer.claude.as_ref().unwrap().use_skills,
            )
            .unwrap()
        };
        let grouped = render_of(r#"      use-skills "a" "b""#);
        let split = render_of(
            r#"      use-skills "a"
      use-skills "b""#,
        );
        assert_eq!(grouped, split);
        assert!(grouped.contains(
            "- Always use the `a` skill.\n\
             - Always use the `b` skill.\n"
        ));
    }
}
